schema_version = "1.0.0"

id = "quick_export_extension"
version = "1.0.0"
name = "Quick Export"
tagline = "Exports the active object's collection if it has exporters"
maintainer = "Marek Hanzelka"

type = "add-on"

website = "https://github.com/Maro-3D/BQE/tree/main"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
